# AI Resume Screening - EDA

## Objectives :
### - Understand dataset structure and quality
### - Identify missing values and anomalies
### - Discover patterns and relationships
### - Prepare data for downstream modeling

## Below are the grouping of columns under different lables

| Type                      | Columns                                                          |
| ------------------------- | ---------------------------------------------------------------- |
|    Candidate Info         | `candidate_id`, `primary_role`, `primary_domain`                 |
|    Experience             | `years_experience`                                               |
|    Education              | `highest_education`, `education_field`, `institution_tier`       |
|    Skills                 | `technical_skills_raw`, `tools_platforms_raw`, `soft_skills_raw` |
|    NLP Text               | `experience_summary`, `project_summary`                          |
|    Flags (VERY IMPORTANT) | `ml_experience_flag`, `cloud_experience_flag`, etc.              |
|    Scores                 | `keyword_density_score`, `profile_completeness_score`            |

##  1. Import Libraries & Setup

In [367]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

## 2.Load Data

In [368]:
 
df = pd.read_csv("../data/parsed_resumes.csv")

print(df.shape)
print(df.info())
print(df.describe())

(5000, 34)
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 34 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   candidate_id                            5000 non-null   str
 1   resume_file_name                        5000 non-null   str
 2   candidate_name                          5000 non-null   str
 3   primary_domain                          5000 non-null   str
 4   primary_role                            5000 non-null   str
 5   years_experience                        5000 non-null   int64
 6   highest_education                       4730 non-null   str
 7   education_field                         4763 non-null   str
 8   institution_tier                        5000 non-null   str
 9   technical_skills_raw                    5000 non-null   str
 10  tools_platforms_raw                     5000 non-null   str
 11  soft_skills_raw                         5000 non-null   str
 12  experience_summary                      5000 non-null   str
 13  project_summary                         5000 non-null   str
 14  key_achievements                        5000 non-null   str
 15  management_experience_flag              5000 non-null   int64
 16  people_management_flag                  5000 non-null   int64
 17  project_management_experience_flag      5000 non-null   int64
 18  agile_scrum_experience_flag             5000 non-null   int64
 19  client_facing_experience_flag           5000 non-null   int64
 20  delivery_lead_experience_flag           5000 non-null   int64
 21  cloud_experience_flag                   5000 non-null   int64
 22  ml_experience_flag                      5000 non-null   int64
 23  compliance_experience_flag              5000 non-null   int64
 24  enterprise_systems_experience_flag      5000 non-null   int64
 25  offshore_onsite_model_experience_flag   5000 non-null   int64
 26  multi_vendor_coordination_flag          5000 non-null   int64
 27  process_compliance_experience_flag      5000 non-null   int64
 28  documentation_heavy_role_flag           5000 non-null   int64
 29  mentoring_experience_flag               5000 non-null   int64
 30  stakeholder_management_experience_flag  5000 non-null   int64
 31  resume_length_words                     5000 non-null   int64
 32  keyword_density_score                   5000 non-null   float64
 33  profile_completeness_score              5000 non-null   float64
dtypes: float64(2), int64(18), str(14)
memory usage: 3.7 MB
None
       years_experience  management_experience_flag  people_management_flag  \
count       5000.000000                 5000.000000             5000.000000
mean           6.733600                    0.388200                0.209200
std            4.026645                    0.487389                0.406778
min            1.000000                    0.000000                0.000000
25%            4.000000                    0.000000                0.000000
50%            6.000000                    0.000000                0.000000
75%            9.000000                    1.000000                0.000000
max           20.000000                    1.000000                1.000000

       project_management_experience_flag  agile_scrum_experience_flag  \
count                         5000.000000                  5000.000000
mean                             0.640000                     0.782600
std                              0.480048                     0.412518
min                              0.000000                     0.000000
25%                              0.000000                     1.000000
50%                              1.000000                     1.000000
75%                              1.000000                     1.000000
max                              1.000000                     1.000000

       client_facing_experience_flag  delivery_lead_experience_flag  \
count                     5000.00000                    5000.000000
mean                         0.76580                       0.298800
std                          0.42354                       0.457778
min                          0.00000                       0.000000
25%                          1.00000                       0.000000
50%                          1.00000                       0.000000
75%                          1.00000                       1.000000
max                          1.00000                       1.000000

       cloud_experience_flag  ml_experience_flag  compliance_experience_flag  \
count             5000.00000          5000.00000                 5000.000000
mean                 0.27760             0.20040                    0.179600
std                  0.44786             0.40034                    0.383892
min                  0.00000             0.00000                    0.000000
25%                  0.00000             0.00000                    0.000000
50%                  0.00000             0.00000                    0.000000
75%                  1.00000             0.00000                    0.000000
max                  1.00000             1.00000                    1.000000

       enterprise_systems_experience_flag  \
count                         5000.000000
mean                             0.558400
std                              0.496627
min                              0.000000
25%                              0.000000
50%                              1.000000
75%                              1.000000
max                              1.000000

       offshore_onsite_model_experience_flag  multi_vendor_coordination_flag  \
count                            5000.000000                     5000.000000
mean                                0.894400                        0.470800
std                                 0.307356                        0.499197
min                                 0.000000                        0.000000
25%                                 1.000000                        0.000000
50%                                 1.000000                        0.000000
75%                                 1.000000                        1.000000
max                                 1.000000                        1.000000

       process_compliance_experience_flag  documentation_heavy_role_flag  \
count                          5000.00000                    5000.000000
mean                              0.76580                       0.661600
std                               0.42354                       0.473213
min                               0.00000                       0.000000
25%                               1.00000                       0.000000
50%                               1.00000                       1.000000
75%                               1.00000                       1.000000
max                               1.00000                       1.000000

       mentoring_experience_flag  stakeholder_management_experience_flag  \
count                5000.000000                             5000.000000
mean                    0.558400                                0.640000
std                     0.496627                                0.480048
min                     0.000000                                0.000000
25%                     0.000000                                0.000000
50%                     1.000000                                1.000000
75%                     1.000000                                1.000000
max                     1.000000                                1.000000

       resume_length_words  keyword_density_score  profile_completeness_score
count          5000.000000            5000.000000                 5000.000000
mean             54.850600               0.577590                    0.751524
std               2.887897               0.187424                    0.115454
min              48.000000               0.250000                    0.550000
25%              53.000000               0.420000                    0.650000
50%              55.000000               0.580000                    0.750000
75%              57.000000               0.740000                    0.850000
max              63.000000               0.900000                    0.950000

In [369]:
df.head(50)

,candidate_id,resume_file_name,candidate_name,primary_domain,primary_role,years_experience,highest_education,education_field,institution_tier,technical_skills_raw,...,enterprise_systems_experience_flag,offshore_onsite_model_experience_flag,multi_vendor_coordination_flag,process_compliance_experience_flag,documentation_heavy_role_flag,mentoring_experience_flag,stakeholder_management_experience_flag,resume_length_words,keyword_density_score,profile_completeness_score
0,CND_100001,DataAnalyst_1.pdf,Candidate_1,Data Science,Data Analyst,7,LLM,Mathematics,Tier-1,"Machine Learning, Power BI, Pandas, Python",...,1,1,1,1,0,1,1,56,0.74,0.61
1,CND_100002,profile_2.pdf,Candidate_2,IT,Senior Software Engineer,10,Masters,Computer Science,Tier-2,"Kubernetes, Git, Docker, Python",...,1,1,1,1,1,1,1,54,0.89,0.89
2,CND_100003,Legal_candidate_3.pdf,Candidate_3,Legal,Compliance Officer,7,LLM,Law,Tier-1,"Due Diligence, Legal Research, Compliance, Con...",...,1,1,1,1,1,1,1,57,0.40,0.56
3,CND_100004,IT_candidate_4.pdf,Candidate_4,IT,Senior Software Engineer,9,LLM,Computer Science,Tier-1,"Kubernetes, AWS, SQL, Docker",...,1,1,1,1,1,1,1,55,0.74,0.89
4,CND_100005,IT_candidate_5.pdf,Candidate_5,IT,Software Engineer,9,Masters,Information Technology,Tier-1,"Java, Kubernetes, Git, AWS",...,1,1,1,1,1,1,1,51,0.58,0.59
5,CND_100006,Data Science_candidate_6.pdf,Candidate_6,Data Science,Junior Data Scientist,2,Bachelors,Mathematics,Tier-1,"NLP, Machine Learning, SQL, Python",...,0,0,0,0,0,0,0,54,0.68,0.93
6,CND_100007,DevOpsEngineer_7.pdf,Candidate_7,IT,DevOps Engineer,9,NaN,Computer Science,Tier-1,"Kubernetes, AWS, SQL, Java",...,1,1,1,1,1,1,1,55,0.81,0.58
7,CND_100008,resume_8_Full_Stack_Developer.pdf,Candidate_8,IT,Full Stack Developer,10,Bachelors,Information Technology,Tier-1,"Kubernetes, AWS, Java, Git",...,1,1,1,1,1,1,1,51,0.41,0.63
8,CND_100009,resume_9_Cloud_Engineer.pdf,Candidate_9,IT,Cloud Engineer,5,Masters,Information Technology,Tier-2,"AWS, Kubernetes, Java, Ptyhon",...,0,1,0,1,1,0,1,52,0.44,0.83
9,CND_100010,resume_10_ML_Engineer.pdf,Candidate_10,Data Science,ML Engineer,5,Masters,Mathematics,Tier-3,"Machine Learning, NLP, Power BI, Pythno",...,0,1,0,1,0,0,1,56,0.28,0.58
10,CND_100011,profile_11.pdf,Candidate_11,Data Science,Data Scientist,7,Masters,Data Science,Tier-2,"Machine Learning, Pandas, NLP, Power BI",...,1,1,1,1,0,1,1,60,0.44,0.73
11,CND_100012,profile_12.pdf,Candidate_12,IT,Senior Software Engineer,17,Masters,Information Technology,Tier-2,"Python, SQL, AWS, Docker",...,1,1,1,1,1,1,1,55,0.84,0.89
12,CND_100013,resume_13_Cloud_Engineer.pdf,Candidate_13,IT,Cloud Engineer,7,MBA,Computer Science,Tier-1,"Python, Linux, Docker, Java",...,1,1,1,1,1,1,1,56,0.45,0.91
13,CND_100014,profile_14.pdf,Candidate_14,HR,HR Executive,3,LLM,Human Resources,Tier-3,"Recruitment, Employee Engagement, Payroll, HRMS",...,0,1,0,0,0,0,0,53,0.32,0.90
14,CND_100015,resume_15_Corporate_Lawyer.pdf,Candidate_15,Legal,Corporate Lawyer,6,MBA,NaN,Tier-3,"Due Diligence, Compliance, Legal Research, Con...",...,1,1,0,1,1,1,1,59,0.53,0.84
15,CND_100016,profile_16.pdf,Candidate_16,IT,DevOps Engineer,4,Bachelors,Information Technology,Tier-3,"Git, AWS, Java, Docker",...,0,1,0,1,1,0,0,58,0.52,0.71
16,CND_100017,SoftwareEngineer_17.pdf,Candidate_17,IT,Software Engineer,6,LLM,Computer Science,Tier-2,"Git, SQL, Kubernetes, Jaav",...,1,1,0,1,1,1,1,50,0.59,0.80
17,CND_100018,IT_candidate_18.pdf,Candidate_18,IT,Software Engineer,7,Masters,Computer Science,Tier-1,"Kubenretes, Git, Java, SQL",...,1,1,1,1,1,1,1,55,0.76,0.64
18,CND_100019,HR_candidate_19.pdf,Candidate_19,HR,Talent Acquisition Specialist,3,LLM,Human Resources,Tier-2,"Employee Engagement, Recruitment, HRMS, HR Ana...",...,0,1,0,0,0,0,0,51,0.75,0.76
19,CND_100020,Data Science_candidate_20.pdf,Candidate_20,Data Science,Data Scientist,10,LLM,Statistics,Tier-3,"Python, Pandas, NLP, Machine Learning",...,1,1,1,1,0,1,1,56,0.86,0.56
20,CND_100021,resume_21_Compliance_Officer.pdf,Candidate_21,Legal,Compliance Officer,10,LLM,Law,Tier-2,"Contract Drafting, Compliance, Legal Research,...",...,1,1,1,1,1,1,1,57,0.85,0.94
21,CND_100022,IT_candidate_22.pdf,Candidate_22,IT,Cloud Engineer,3,Bachelors,Computer Science,Tier-2,"Java, SQL, Kubernetes, Linux",...,0,1,0,0,1,0,0,52,0.40,0.58
22,CND_100023,profile_23.pdf,Candidate_23,Engineering,Junior Mechanical Engineer,1,Bachelors,Mechanical Engineering,Tier-2,"SolidWorks, CAD, Manufacturing, Quality Control",...,0,0,0,0,0,0,0,56,0.51,0.84
23,CND_100024,IT_candidate_24.pdf,Candidate_24,IT,Full Stack Developer,6,LLM,Information Technology,Tier-2,"Java, SQL, Docker, AWS",...,1,1,0,1,1,1,1,55,0.71,0.72
24,CND_100025,DataScientist_25.pdf,Candidate_25,Data Science,Data Scientist,10,LLM,Statistics,Tier-3,"TensorFlow, Power BI, SQL, NLP",...,1,1,1,1,0,1,1,58,0.71,0.66
25,CND_100026,profile_26.pdf,Candidate_26,IT,Software Engineer,4,LLM,Information Technology,Tier-3,"Kubernetes, SQL, Linux, Git",...,0,1,0,1,1,0,0,54,0.61,0.69
26,CND_100027,profile_27.pdf,Candidate_27,IT,Senior Software Engineer,12,Bachelors,Information Technology,Tier-1,"Kubernetes, Python, SQL, Java",...,1,1,1,1,1,1,1,55,0.45,0.83
27,CND_100028,IT_candidate_28.pdf,Candidate_28,IT,Junior Software Engineer,1,Bachelors,Computer Science,Tier-3,"AWS, SQL, Java, Kubernetes",...,0,0,0,0,1,0,0,55,0.87,0.58
28,CND_100029,DevOpsEngineer_29.pdf,Candidate_29,IT,DevOps Engineer,9,MBA,Computer Science,Tier-3,"Kubernetes, Git, AWS, Linux",...,1,1,1,1,1,1,1,54,0.30,0.55
29,CND_100030,DevOpsEngineer_30.pdf,Candidate_30,IT,DevOps Engineer,10,MBA,Computer Science,Tier-2,"AWS, Python, Java, Docker",...,1,1,1,1,1,1,1,57,0.64,0.88
30,CND_100031,resume_31_Compliance_Officer.pdf,Candidate_31,Legal,Compliance Officer,4,MBA,Law,Tier-3,"Due Diligence, Legal Research, Compliance, Con...",...,0,1,0,1,1,0,0,58,0.54,0.66
31,CND_100032,profile_32.pdf,Candidate_32,Management,Management Consultant,16,MBA,Business Administration,Tier-1,"Risk Management, Strategy, Stakeholder Managem...",...,1,1,1,1,1,1,1,56,0.68,0.77
32,CND_100033,SoftwareEngineer_33.pdf,Candidate_33,IT,Software Engineer,8,MBA,Information Technology,Tier-1,"Linux, SQL, Kubernetes, Python",...,1,1,1,1,1,1,1,53,0.55,0.60
33,CND_100034,profile_34.pdf,Candidate_34,HR,Talent Acquisition Specialist,7,Bachelors,Psychology,Tier-3,"Employee Engagement, Payroll, Recruitment, HR ...",...,1,1,1,1,0,1,1,51,0.90,0.75
34,CND_100035,IT_candidate_35.pdf,Candidate_35,IT,DevOps Engineer,10,LLM,Computer Science,Tier-1,"SQL, Docker, AWS, Linux",...,1,1,1,1,1,1,1,53,0.33,0.94
35,CND_100036,IT_candidate_36.pdf,Candidate_36,IT,Junior Software Engineer,4,MBA,Information Technology,Tier-1,"Java, AWS, Kubernetes, Python",...,0,1,0,1,1,0,0,53,0.65,0.64
36,CND_100037,Data Science_candidate_37.pdf,Candidate_37,Data Science,Data Scientist,6,Masters,Statistics,Tier-1,"Pandas, Python, TensorFlow, Power BI",...,1,1,0,1,0,1,1,57,0.36,0.58
37,CND_100038,Legal_candidate_38.pdf,Candidate_38,Legal,Corporate Lawyer,10,MBA,Law,Tier-2,"Compliance, Contract Drafting, Due Diligence, ...",...,1,1,1,1,1,1,1,54,0.80,0.59
38,CND_100039,SeniorSoftwareEngineer_39.pdf,Candidate_39,IT,Senior Software Engineer,17,MBA,Computer Science,Tier-3,"AWS, SQL, Docker, Python",...,1,1,1,1,1,1,1,54,0.67,0.67
39,CND_100040,profile_40.pdf,Candidate_40,IT,DevOps Engineer,8,Bachelors,Computer Science,Tier-1,"Docker, Python, Linux, SQL",...,1,1,1,1,1,1,1,54,0.81,0.84
40,CND_100041,SeniorProjectManager_41.pdf,Candidate_41,Management,Senior Project Manager,9,Bachelors,Business Administration,Tier-2,"Risk Management, Strategy, Stakeholder Managem...",...,1,1,1,1,1,1,1,56,0.67,0.60
41,CND_100042,IT_candidate_42.pdf,Candidate_42,IT,Junior Software Engineer,3,NaN,Information Technology,Tier-2,"Linux, Python, Git, Java",...,0,1,0,0,1,0,0,57,0.87,0.89
42,CND_100043,FullStackDeveloper_43.pdf,Candidate_43,IT,Full Stack Developer,8,Bachelors,Computer Science,Tier-1,"SQL, Python, Kubernetes, Docker",...,1,1,1,1,1,1,1,52,0.46,0.61
43,CND_100044,Legal_candidate_44.pdf,Candidate_44,Legal,Legal Associate,3,Bachelors,Law,Tier-2,"Compliance, Contract Drafting, Due Diligence, ...",...,0,1,0,0,1,0,0,56,0.58,0.59
44,CND_100045,DevOpsEngineer_45.pdf,Candidate_45,IT,DevOps Engineer,3,MBA,Information Technology,Tier-3,"AWS, Kubernetes, SQL, Python",...,0,1,0,0,1,0,0,55,0.59,0.73
45,CND_100046,DataAnalyst_46.pdf,Candidate_46,Data Science,Data Analyst,4,LLM,Data Science,Tier-1,"Power BI, Pandas, SQL, Machine Learning",...,0,1,0,1,0,0,0,56,0.73,0.70
46,CND_100047,resume_47_Junior_Software_Engineer.pdf,Candidate_47,IT,Junior Software Engineer,3,MBA,Information Technology,Tier-2,"Java, Kubernetes, Docker, Git",...,0,1,0,0,1,0,0,57,0.62,0.87
47,CND_100048,HRExecutive_48.pdf,Candidate_48,HR,HR Executive,3,LLM,Psychology,Tier-2,"HRMS, Recruitment, HR Analytics, Payroll",...,0,1,0,0,0,0,0,55,0.72,0.86
48,CND_100049,resume_49_Data_Analyst.pdf,Candidate_49,Data Science,Data Analyst,3,MBA,Mathematics,Tier-3,"Machine Learning, Power BI, SQL, Python",...,0,1,0,0,0,0,0,58,0.45,0.64
49,CND_100050,profile_50.pdf,Candidate_50,Management,Project Coordinator,1,Bachelors,Management,Tier-2,"Stakeholder Management, Risk Management, Strat...",...,0,0,0,0,1,0,0,56,0.85,0.89

In [370]:
df.columns

Index(['candidate_id', 'resume_file_name', 'candidate_name', 'primary_domain',
       'primary_role', 'years_experience', 'highest_education',
       'education_field', 'institution_tier', 'technical_skills_raw',
       'tools_platforms_raw', 'soft_skills_raw', 'experience_summary',
       'project_summary', 'key_achievements', 'management_experience_flag',
       'people_management_flag', 'project_management_experience_flag',
       'agile_scrum_experience_flag', 'client_facing_experience_flag',
       'delivery_lead_experience_flag', 'cloud_experience_flag',
       'ml_experience_flag', 'compliance_experience_flag',
       'enterprise_systems_experience_flag',
       'offshore_onsite_model_experience_flag',
       'multi_vendor_coordination_flag', 'process_compliance_experience_flag',
       'documentation_heavy_role_flag', 'mentoring_experience_flag',
       'stakeholder_management_experience_flag', 'resume_length_words',
       'keyword_density_score', 'profile_completeness_score'],
      dtype='str')

In [371]:
df.columns.value_counts()

candidate_id                              1
resume_file_name                          1
candidate_name                            1
primary_domain                            1
primary_role                              1
years_experience                          1
highest_education                         1
education_field                           1
institution_tier                          1
technical_skills_raw                      1
tools_platforms_raw                       1
soft_skills_raw                           1
experience_summary                        1
project_summary                           1
key_achievements                          1
management_experience_flag                1
people_management_flag                    1
project_management_experience_flag        1
agile_scrum_experience_flag               1
client_facing_experience_flag             1
delivery_lead_experience_flag             1
cloud_experience_flag                     1
ml_experience_flag                        1
compliance_experience_flag                1
enterprise_systems_experience_flag        1
offshore_onsite_model_experience_flag     1
multi_vendor_coordination_flag            1
process_compliance_experience_flag        1
documentation_heavy_role_flag             1
mentoring_experience_flag                 1
stakeholder_management_experience_flag    1
resume_length_words                       1
keyword_density_score                     1
profile_completeness_score                1
Name: count, dtype: int64

## Right now our columns are raw.
## We need to organize them into logical feature groups → this helps in:

   ### 1 EDA
   ### 2 Feature engineering
   ### 3 Final report

In [372]:
## Group the features : 

# Candidate Identity-->'candidate_id','resume_file_name','candidate_name'
# Core Profile--> 'primary_domain','primary_role','years_experience'--->Used for:Domain match,Role match,Experience scoring
# Education--> 'highest_education','education_field','institution_tier'
# Skills--->'technical_skills_raw','tools_platforms_raw','soft_skills_raw'
# Text Data--->'experience_summary','project_summary','key_achievements'(NLP)
#flag-->col for col in df.columns if 'flag' in col
#Scoring Metrics-->'resume_length_words','keyword_density_score','profile_completeness_score'--> used for Resume quality scoring

In [373]:
id_cols = [
    'candidate_id',
    'resume_file_name',
    'candidate_name'
]

In [374]:
profile_cols = [
    'primary_domain',
    'primary_role',
    'years_experience'
]

In [375]:
education_cols = [
    'highest_education',
    'education_field',
    'institution_tier'
]

In [376]:
skills_cols = [
    'technical_skills_raw',
    'tools_platforms_raw',
    'soft_skills_raw'
]

In [377]:
text_cols = [
    'experience_summary',
    'project_summary',
    'key_achievements'
]

In [378]:
flag_cols = [
    col for col in df.columns if 'flag' in col
]

In [379]:
score_cols = [
    'resume_length_words',
    'keyword_density_score',
    'profile_completeness_score'
]

# Combine All to Create a dictionary:

In [380]:

column_groups = {
    "id": id_cols,
    "profile": profile_cols,
    "education": education_cols,
    "skills": skills_cols,
    "text": text_cols,
    "flags": flag_cols,
    "scores": score_cols
}

# Print to show the group and seperate list

In [381]:

for group, cols in column_groups.items():
    print(f"\n{group.upper()}:\n", cols)

ID:
 ['candidate_id', 'resume_file_name', 'candidate_name']

PROFILE:
 ['primary_domain', 'primary_role', 'years_experience']

EDUCATION:
 ['highest_education', 'education_field', 'institution_tier']

SKILLS:
 ['technical_skills_raw', 'tools_platforms_raw', 'soft_skills_raw']

TEXT:
 ['experience_summary', 'project_summary', 'key_achievements']

FLAGS:
 ['management_experience_flag', 'people_management_flag', 'project_management_experience_flag', 'agile_scrum_experience_flag', 'client_facing_experience_flag', 'delivery_lead_experience_flag', 'cloud_experience_flag', 'ml_experience_flag', 'compliance_experience_flag', 'enterprise_systems_experience_flag', 'offshore_onsite_model_experience_flag', 'multi_vendor_coordination_flag', 'process_compliance_experience_flag', 'documentation_heavy_role_flag', 'mentoring_experience_flag', 'stakeholder_management_experience_flag']

SCORES:
 ['resume_length_words', 'keyword_density_score', 'profile_completeness_score']

In [382]:
important_flags = [
    'ml_experience_flag',
    'cloud_experience_flag',
    'project_management_experience_flag'
]

In [383]:
df['flag_score'] = df[important_flags].mean(axis=1)

# Score Normalization

In this step, we are converting different score values into a common scale between 0 and 1.

This process is called **Normalization**.

Machine Learning models work better when all feature values are in a similar range.

---

# 1. Keyword Score Normalization

```python
df['keyword_score_norm'] = df['keyword_density_score'] / 100
```

## What it does

`keyword_density_score` is originally in percentage format.

Example:

- 80%
- 65%
- 40%

We divide by 100 to convert it into values between 0 and 1.

### Example

```python
80 / 100 = 0.80
```

So:

- 80% → 0.80
- 50% → 0.50

---

# 2. Profile Completeness Score Normalization

```python
df['profile_score_norm'] = df['profile_completeness_score'] / 100
```

## What it does

Profile completeness is also a percentage value.

Example:

- 90%
- 70%
- 40%

We convert it into normalized decimal values.

### Example

```python
90 / 100 = 0.90
```

---

# 3. Resume Length Score Normalization

```python
df['length_score'] = df['resume_length_words'] / df['resume_length_words'].max()
```

## What it does

Different resumes have different word counts.

Example:

- Resume A = 500 words
- Resume B = 1000 words
- Resume C = 1500 words

We divide each resume length by the maximum resume length.

This converts all values between 0 and 1.

---

## Example

If maximum resume length is:

```python
1500
```

Then:

```python
500 / 1500 = 0.33
1000 / 1500 = 0.66
1500 / 1500 = 1.0
```

---

# Why We Do This

Normalization helps because:

- All features become comparable
- Large values do not dominate small values
- Machine Learning models perform better
- Training becomes more stable

---

# Simple Summary

We are converting all scores into a common scale (0 to 1)
so the Machine Learning model can understand and compare them properly.

In [384]:
df['keyword_score_norm'] = df['keyword_density_score'] / 100
df['profile_score_norm'] = df['profile_completeness_score'] / 100
df['length_score'] = df['resume_length_words'] / df['resume_length_words'].max()

## What we are going to do the next

### Resume data (skills, experience, etc.) -->Done

### Now we want to answer:

####  “Is this candidate good for a job?”

#### So we need to create simple scores.

## Computer understands lists, not messy text hence we create a list from technological raw data
### Create a method to retrun list and clean text with lower case and split where there is ','

In [385]:


def clean_skills(text):
    if pd.isnull(text):
        return []
    return text.lower().split(",")

# Now apply this to the technical_skills_raw to extract in the list and lower case

In [386]:

df['tech_skills_clean']=df['technical_skills_raw'].apply(clean_skills)

In [387]:
df[['technical_skills_raw', 'tech_skills_clean']].head()

,technical_skills_raw,tech_skills_clean
0,"Machine Learning, Power BI, Pandas, Python","[machine learning, power bi, pandas, python]"
1,"Kubernetes, Git, Docker, Python","[kubernetes, git, docker, python]"
2,"Due Diligence, Legal Research, Compliance, Con...","[due diligence, legal research, compliance, ..."
3,"Kubernetes, AWS, SQL, Docker","[kubernetes, aws, sql, docker]"
4,"Java, Kubernetes, Git, AWS","[java, kubernetes, git, aws]"

In [388]:
# ------------------------------------------------------------
# SKILL SCORE EXPLANATION
# ------------------------------------------------------------

# Every job requires different skills.
# So first we extract required skills from the Job Description (JD).

# Example:
# Data Scientist -> python, sql, machine learning
# Java Developer -> java, spring
# Finance Analyst -> excel, finance
# Lawyer -> legal research

# Example JD:
# "Looking for Python, SQL and AWS developer"

# Extracted JD skills:
# jd_skills = ['python', 'sql', 'aws']

# ------------------------------------------------------------
# RESUME SKILL EXTRACTION
# ------------------------------------------------------------

# Then we extract skills from the candidate resume.

# Example:
# candidate_skills = ['python', 'sql']

# ------------------------------------------------------------
# SKILL MATCH CALCULATION
# ------------------------------------------------------------

# Compare candidate skills with JD skills.

# JD Skills        = ['python', 'sql', 'aws']
# Candidate Skills = ['python', 'sql']

# Matched skills = 2
# Total JD skills = 3

# Skill Score = 2 / 3 = 0.66

# Final Skill Match = 66%

# ------------------------------------------------------------
# PURPOSE
# ------------------------------------------------------------

# Higher score means:
# - Candidate skills match job requirements better

# Lower score means:
# - Candidate is missing important skills

In [389]:
def skill_match(candidate_skills, jd_skills):
    match = 0
    
    for skill in jd_skills:
        if skill in candidate_skills:
            match += 1
            
    return match / len(jd_skills)

In [390]:
jd_skills = ['python', 'sql', 'aws','machine learning','power bi', 'nlp', 'pandas']
df['skill_match_score'] = df['tech_skills_clean'].apply(
    lambda x: skill_match(x, jd_skills)
)

In [391]:
df[['tech_skills_clean', 'skill_match_score']].head(100)

                                    tech_skills_clean  skill_match_score
0     [machine learning,  power bi,  pandas,  python]           0.142857
1                [kubernetes,  git,  docker,  python]           0.000000
2   [due diligence,  legal research,  compliance, ...           0.000000
3                   [kubernetes,  aws,  sql,  docker]           0.000000
4                     [java,  kubernetes,  git,  aws]           0.000000
..                                                ...                ...
95  [payroll,  hr analytics,  employee engagement,...           0.000000
96                  [linux,  sql,  jaav,  kubernetes]           0.000000
97                 [pandas,  sql,  power bi,  python]           0.142857
98                  [sql,  python,  kubernetes,  git]           0.142857
99  [payroll,  hrms,  employee engagement,  hr ana...           0.000000

[100 rows x 2 columns]

### We observed that there is spelling mispelt in many skill,  like pythono,pythno,jaav, we need to fix this
### how to fix it ??

--- Use Python built-in library get_close_matches

In [392]:
from difflib import get_close_matches
correct_skills = [
    "python", "sql", "java", "machine learning", 
    "aws", "excel", "power bi"
]
def fix_skill(skill):
    match = get_close_matches(skill, correct_skills, n=1, cutoff=0.6)
    
    if match:
        return match[0]
    else:
        return skill

In [393]:
#Apply to skill column 

def clean_and_fix_skills(skills):
    if pd.isnull(skills):
        return []
    
    skills_list = skills.lower().split(",")
    
    fixed = [fix_skill(skill.strip()) for skill in skills_list]
    
    return fixed

In [394]:
#Apply to dataframe
df['tech_skills_clean'] = df['technical_skills_raw'].apply(clean_and_fix_skills)

In [395]:
df[['tech_skills_clean', 'skill_match_score']].head(50)

                                    tech_skills_clean  skill_match_score
0        [machine learning, power bi, pandas, python]           0.142857
1                   [kubernetes, git, docker, python]           0.000000
2   [due diligence, legal research, compliance, co...           0.000000
3                      [kubernetes, aws, sql, docker]           0.000000
4                        [java, kubernetes, git, aws]           0.000000
5                [nlp, machine learning, sql, python]           0.142857
6                        [kubernetes, aws, sql, java]           0.000000
7                        [kubernetes, aws, java, git]           0.000000
8                     [aws, kubernetes, java, python]           0.142857
9           [machine learning, nlp, power bi, python]           0.142857
10          [machine learning, pandas, nlp, power bi]           0.142857
11                         [python, sql, aws, docker]           0.142857
12                      [python, linux, docker, java]           0.142857
13  [recruitment, employee engagement, payroll, hrms]           0.000000
14  [due diligence, compliance, legal research, co...           0.000000
15                           [git, aws, java, docker]           0.000000
16                       [git, sql, kubernetes, java]           0.000000
17                       [kubenretes, git, java, sql]           0.000000
18  [employee engagement, recruitment, hrms, hr an...           0.000000
19            [python, pandas, nlp, machine learning]           0.142857
20  [contract drafting, compliance, legal research...           0.000000
21                     [java, sql, kubernetes, linux]           0.000000
22  [solidworks, cad, manufacturing, quality control]           0.000000
23                           [java, sql, docker, aws]           0.000000
24                   [tensorflow, power bi, sql, nlp]           0.000000
25                      [kubernetes, sql, linux, git]           0.000000
26                    [kubernetes, python, sql, java]           0.000000
27                       [aws, sql, java, kubernetes]           0.142857
28                      [kubernetes, git, aws, linux]           0.000000
29                        [aws, python, java, docker]           0.142857
30  [due diligence, legal research, compliance, co...           0.000000
31  [risk management, strategy, stakeholder manage...           0.000000
32                   [linux, sql, kubernetes, python]           0.000000
33  [employee engagement, payroll, recruitment, hr...           0.000000
34                          [sql, docker, aws, linux]           0.142857
35                    [java, aws, kubernetes, python]           0.000000
36             [pandas, python, tensorflow, power bi]           0.142857
37  [compliance, contract drafting, due diligence,...           0.000000
38                         [aws, sql, docker, python]           0.142857
39                       [docker, python, linux, sql]           0.000000
40  [risk management, strategy, stakeholder manage...           0.000000
41                         [linux, python, git, java]           0.000000
42                  [sql, python, kubernetes, docker]           0.142857
43  [compliance, contract drafting, due diligence,...           0.000000
44                     [aws, kubernetes, sql, python]           0.142857
45          [power bi, pandas, sql, machine learning]           0.142857
46                    [java, kubernetes, docker, git]           0.000000
47         [hrms, recruitment, hr analytics, payroll]           0.000000
48          [machine learning, power bi, sql, python]           0.142857
49  [stakeholder management, risk management, stra...           0.000000

# Fuzzy matching techniques were used to correct spelling variations in skills (e.g., ‘ptyhon’ → ‘python’) to improve matching accuracy

## Experience Score

### What are we doing?

### We want to answer:

####  “Does candidate have enough experience?”
##### Assume job requirement 3

In [396]:
required_exp = 3
df['exp_match_score'] = df['years_experience'] / required_exp

In [397]:
df['exp_match_score']

0       2.333333
1       3.333333
2       2.333333
3       3.000000
4       3.000000
          ...
4995    2.000000
4996    3.333333
4997    0.333333
4998    2.666667
4999    1.000000
Name: exp_match_score, Length: 5000, dtype: float64

In [398]:
# limited to 1 year
df['exp_match_score'] = df['exp_match_score'].apply(lambda x: min(x, 1))

In [399]:
# Quick check 
df[['years_experience', 'exp_match_score']].head()

   years_experience  exp_match_score
0                 7              1.0
1                10              1.0
2                 7              1.0
3                 9              1.0
4                 9              1.0

## User Input: Experience

###  “The required experience parameter is designed to be dynamic and can be adjusted based on job requirements or user input via UI.

#### Note:
We will NOT hardcode values like "3 years" here.  
Instead, we are building a dynamic input system so that:
- The user can enter the required experience from the UI
- The model will automatically update the score based on the input

---

##  Example Inputs:

### • 2 years  
### • 5 years  

---

##  Model Behavior

#### Our model updates automatically

---

##  Streamlit Input Example

```python
required_exp = st.number_input(
    "Enter required experience",
    min_value=0,
    max_value=20,
    value=3
)

## 📊 Domain Score

 **Question:**  
“Is the candidate from the same field as the job?”

---

## 🎯 Example

### 💼 Job:
**Data Science**

---

### 👤 Candidate 1:
**Data Science**

👉 **Score = 1 ✅** (Perfect match)

---

### 👤 Candidate 2:
**Finance**

👉 **Score = 0 ❌** (No match)

In [400]:
domain_map = {
    "data science": ["data science", "data analyst", "machine learning", "ai"],
    "finance": ["finance", "accounting", "banking"],
    "law": ["law", "legal", "advocate"],
    "java developer": ["java", "spring", "backend"]
}

In [401]:
def domain_match_func(primary_domain, target_domain):
    primary_domain = str(primary_domain).lower()
    target_domain = target_domain.lower()

    if target_domain in domain_map:
        keywords = domain_map[target_domain]

        for k in keywords:
            if k in primary_domain:
                return 1

    return 0

In [402]:
#Create Domain Score
target_domain = "data science"

df['domain_match'] = df['primary_domain'].apply(
    lambda x: domain_match_func(x, target_domain)
)

In [403]:
# check the 
df[['primary_domain', 'domain_match']].head()

  primary_domain  domain_match
0   Data Science             1
1             IT             0
2          Legal             0
3             IT             0
4             IT             0

In [404]:
df.head()

,candidate_id,resume_file_name,candidate_name,primary_domain,primary_role,years_experience,highest_education,education_field,institution_tier,technical_skills_raw,...,keyword_density_score,profile_completeness_score,flag_score,keyword_score_norm,profile_score_norm,length_score,tech_skills_clean,skill_match_score,exp_match_score,domain_match
0,CND_100001,DataAnalyst_1.pdf,Candidate_1,Data Science,Data Analyst,7,LLM,Mathematics,Tier-1,"Machine Learning, Power BI, Pandas, Python",...,0.74,0.61,0.666667,0.0074,0.0061,0.888889,"[machine learning, power bi, pandas, python]",0.142857,1.0,1
1,CND_100002,profile_2.pdf,Candidate_2,IT,Senior Software Engineer,10,Masters,Computer Science,Tier-2,"Kubernetes, Git, Docker, Python",...,0.89,0.89,0.333333,0.0089,0.0089,0.857143,"[kubernetes, git, docker, python]",0.000000,1.0,0
2,CND_100003,Legal_candidate_3.pdf,Candidate_3,Legal,Compliance Officer,7,LLM,Law,Tier-1,"Due Diligence, Legal Research, Compliance, Con...",...,0.40,0.56,0.333333,0.0040,0.0056,0.904762,"[due diligence, legal research, compliance, co...",0.000000,1.0,0
3,CND_100004,IT_candidate_4.pdf,Candidate_4,IT,Senior Software Engineer,9,LLM,Computer Science,Tier-1,"Kubernetes, AWS, SQL, Docker",...,0.74,0.89,0.666667,0.0074,0.0089,0.873016,"[kubernetes, aws, sql, docker]",0.000000,1.0,0
4,CND_100005,IT_candidate_5.pdf,Candidate_5,IT,Software Engineer,9,Masters,Information Technology,Tier-1,"Java, Kubernetes, Git, AWS",...,0.58,0.59,0.666667,0.0058,0.0059,0.809524,"[java, kubernetes, git, aws]",0.000000,1.0,0

# NLP Applied 

## “How similar is resume text to job description?”
### Good Match: 
#### resume ="I worked on Python, machine learning, data analysis"
#### jd=We need Python and machine learning skills
#### These are similar → high score

### Bad match :

#### "Worked in finance and accounting"
#### Not similar → low score

In [405]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [406]:
def compute_similarity(resume, jd):
    
    # Convert 2 texts into numbers
    tfidf = TfidfVectorizer()
    vectors = tfidf.fit_transform([resume, jd])
    
    # Compare similarity
    score = cosine_similarity(vectors[0], vectors[1])
    
    return score[0][0]

In [407]:
def normalize_text(text):
    text = text.lower()
    text = text.replace("ml", "machine learning")
    text = text.replace("ai", "artificial intelligence")
    return text

In [408]:
resume = "Python machine learning experience"
jd = "Looking for Python, ML, SQL"

resume = normalize_text(resume)
jd = normalize_text(jd)

score = compute_similarity(jd, resume)
print(score )

0.4501755023269897

| Score Range | Meaning          |
| ----------- | ---------------- |
| 0.0 – 0.2   |  Very low match |
| 0.2 – 0.5   |  Partial match |
| 0.5 – 0.8   |  Good match     |
| 0.8 – 1.0   |  Strong match  |

In [409]:
#Apply in dataframe 

df['nlp_score'] = df.apply(
    lambda x: compute_similarity(
        str(x['experience_summary']),
        "Hands-on data science professional with 3+ year"
    ),
    axis=1
)

In [410]:
#check 

df[['experience_summary', 'nlp_score']].head(50)

                                   experience_summary  nlp_score
0   Hands-on data science professional with 7+ yea...   0.355934
1   Over 10 years delivering solutions in it, coll...   0.047435
2   Hands-on legal professional with 7+ years of e...   0.212773
3   Hands-on it professional with 9+ years of end-...   0.212773
4   Hands-on it professional with 9+ years of end-...   0.212773
5   Hands-on data science professional with 2+ yea...   0.355934
6   9+ years of experience in it roles, working ac...   0.000000
7   Over 10 years delivering solutions in it, coll...   0.047435
8   Over 5 years delivering solutions in it, colla...   0.048851
9   Hands-on data science professional with 5+ yea...   0.355934
10  7+ years of experience in data science roles, ...   0.094699
11  Over 17 years delivering solutions in it, coll...   0.047435
12  7+ years of experience in it roles, working ac...   0.000000
13  3+ years of experience in hr roles, working ac...   0.000000
14  Hands-on legal professional with 6+ years of e...   0.212773
15  4+ years of experience in it roles, working ac...   0.000000
16  Over 6 years delivering solutions in it, colla...   0.048851
17  Hands-on it professional with 7+ years of end-...   0.212773
18  Hands-on hr professional with 3+ years of end-...   0.212773
19  10+ years of experience in data science roles,...   0.092302
20  10+ years of experience in legal roles, workin...   0.000000
21  Over 3 years delivering solutions in it, colla...   0.048851
22  Hands-on engineering professional with 1+ year...   0.212773
23  Hands-on it professional with 6+ years of end-...   0.212773
24  Over 10 years delivering solutions in data sci...   0.154458
25  4+ years of experience in it roles, working ac...   0.000000
26  Hands-on it professional with 12+ years of end...   0.207105
27  Over 1 years delivering solutions in it, colla...   0.048851
28  Hands-on it professional with 9+ years of end-...   0.212773
29  10+ years of experience in it roles, working a...   0.000000
30  4+ years of experience in legal roles, working...   0.000000
31  Hands-on management professional with 16+ year...   0.207105
32  Hands-on it professional with 8+ years of end-...   0.212773
33  Over 7 years delivering solutions in hr, colla...   0.048851
34  Over 10 years delivering solutions in it, coll...   0.047435
35  Hands-on it professional with 4+ years of end-...   0.212773
36  6+ years of experience in data science roles, ...   0.094699
37  Over 10 years delivering solutions in legal, c...   0.047435
38  Over 17 years delivering solutions in it, coll...   0.047435
39  8+ years of experience in it roles, working ac...   0.000000
40  Over 9 years delivering solutions in managemen...   0.048851
41  Over 3 years delivering solutions in it, colla...   0.048851
42  8+ years of experience in it roles, working ac...   0.000000
43  3+ years of experience in legal roles, working...   0.000000
44  Over 3 years delivering solutions in it, colla...   0.048851
45  Over 4 years delivering solutions in data scie...   0.159064
46  3+ years of experience in it roles, working ac...   0.000000
47  Hands-on hr professional with 3+ years of end-...   0.212773
48  Hands-on data science professional with 3+ yea...   0.355934
49  Hands-on management professional with 1+ years...   0.212773

## We found that education filed also add weightage to the final score hence we add the education field

In [411]:

valid_education = [
    "data science",
    "computer science",
    "information technology",
    "artificial intelligence",
    "machine learning"
]

In [412]:
def check_education(edu):
    if pd.isnull(edu):
        return 0
    
    edu = edu.lower()
    
    # Full forms (normal match)
    full_forms = [
        "data science",
        "computer science",
        "information technology",
        "artificial intelligence",
        "machine learning"
    ]
    
    for f in full_forms:
        if f in edu:
            return 1
    
    # Short forms (exact match)
    short_forms = ["it", "ai", "cs","ds"]
    
    for s in short_forms:
        if edu.strip() == s:
            return 1
    
    return 0

In [413]:
df['education_match'] = df['education_field'].apply(check_education)

In [414]:
df[['education_field', 'education_match']].head(50)

            education_field  education_match
0               Mathematics                0
1          Computer Science                1
2                       Law                0
3          Computer Science                1
4    Information Technology                1
5               Mathematics                0
6          Computer Science                1
7    Information Technology                1
8    Information Technology                1
9               Mathematics                0
10             Data Science                1
11   Information Technology                1
12         Computer Science                1
13          Human Resources                0
14                      NaN                0
15   Information Technology                1
16         Computer Science                1
17         Computer Science                1
18          Human Resources                0
19               Statistics                0
20                      Law                0
21         Computer Science                1
22   Mechanical Engineering                0
23   Information Technology                1
24               Statistics                0
25   Information Technology                1
26   Information Technology                1
27         Computer Science                1
28         Computer Science                1
29         Computer Science                1
30                      Law                0
31  Business Administration                0
32   Information Technology                1
33               Psychology                0
34         Computer Science                1
35   Information Technology                1
36               Statistics                0
37                      Law                0
38         Computer Science                1
39         Computer Science                1
40  Business Administration                0
41   Information Technology                1
42         Computer Science                1
43                      Law                0
44   Information Technology                1
45             Data Science                1
46   Information Technology                1
47               Psychology                0
48              Mathematics                0
49               Management                0

In [415]:
df['final_score'] = (
    0.25 * df['skill_match_score'] +
    0.25 * df['exp_match_score'] +  
    0.15 * df['domain_match'] +
    0.15 * df['education_match'] +
    0.1 * df['flag_score'] +
    0.05 * df['keyword_score_norm'] +
    0.05 * df['profile_score_norm']
)

## skill + exp + domain + education + flags → final_score → selected

In [416]:
df[['skill_match_score', 'exp_match_score', 'domain_match','education_match','flag_score','final_score']].head(50)

,skill_match_score,exp_match_score,domain_match,education_match,flag_score,final_score
0,0.142857,1.000000,1,0,0.666667,0.503056
1,0.000000,1.000000,0,1,0.333333,0.434223
2,0.000000,1.000000,0,0,0.333333,0.283813
3,0.000000,1.000000,0,1,0.666667,0.467482
4,0.000000,1.000000,0,1,0.666667,0.467252
5,0.142857,0.666667,1,0,0.333333,0.386519
6,0.000000,1.000000,0,1,0.666667,0.467362
7,0.000000,1.000000,0,1,0.666667,0.467187
8,0.142857,1.000000,0,1,0.666667,0.503016
9,0.142857,1.000000,1,0,0.666667,0.502811
10,0.142857,1.000000,1,1,0.666667,0.652966
11,0.142857,1.000000,0,1,0.666667,0.503246
12,0.142857,1.000000,0,1,0.333333,0.469728
13,0.000000,1.000000,0,0,0.000000,0.250610
14,0.000000,1.000000,0,0,0.333333,0.284018
15,0.000000,1.000000,0,1,0.333333,0.433948
16,0.000000,1.000000,0,1,0.333333,0.434028
17,0.000000,1.000000,0,1,0.333333,0.434033
18,0.000000,1.000000,0,0,0.000000,0.250755
19,0.142857,1.000000,1,0,0.666667,0.503091
20,0.000000,1.000000,0,0,0.333333,0.284228
21,0.000000,1.000000,0,1,0.000000,0.400490
22,0.000000,0.333333,0,0,0.000000,0.084008
23,0.000000,1.000000,0,1,0.666667,0.467382
24,0.000000,1.000000,1,0,0.666667,0.467352
25,0.000000,1.000000,0,1,0.000000,0.400650
26,0.000000,1.000000,0,1,0.333333,0.433973
27,0.142857,0.333333,0,1,0.333333,0.303106
28,0.000000,1.000000,0,1,0.666667,0.467092
29,0.142857,1.000000,0,1,0.666667,0.503141
30,0.000000,1.000000,0,0,0.000000,0.250600
31,0.000000,1.000000,0,0,0.333333,0.284058
32,0.000000,1.000000,0,1,0.333333,0.433908
33,0.000000,1.000000,0,0,0.333333,0.284158
34,0.142857,1.000000,0,1,0.666667,0.503016
35,0.000000,1.000000,0,1,0.333333,0.433978
36,0.142857,1.000000,1,0,0.666667,0.502851
37,0.000000,1.000000,0,0,0.333333,0.284028
38,0.142857,1.000000,0,1,0.666667,0.503051
39,0.000000,1.000000,0,1,0.333333,0.434158
40,0.000000,1.000000,0,0,0.333333,0.283968
41,0.000000,1.000000,0,1,0.000000,0.400880
42,0.142857,1.000000,0,1,0.333333,0.469583
43,0.000000,1.000000,0,0,0.000000,0.250585
44,0.142857,1.000000,0,1,0.333333,0.469708
45,0.142857,1.000000,1,1,0.333333,0.619763
46,0.000000,1.000000,0,1,0.000000,0.400745
47,0.000000,1.000000,0,0,0.000000,0.250790
48,0.142857,1.000000,1,0,0.333333,0.469593
49,0.000000,0.333333,0,0,0.000000,0.084203

## Apply model
### If score > 0.6 → good candidate

In [417]:

df['selected'] = df['final_score'].apply(lambda x: 1 if x > 0.60 else 0)

In [418]:
df.head(50)

,candidate_id,resume_file_name,candidate_name,primary_domain,primary_role,years_experience,highest_education,education_field,institution_tier,technical_skills_raw,...,profile_score_norm,length_score,tech_skills_clean,skill_match_score,exp_match_score,domain_match,nlp_score,education_match,final_score,selected
0,CND_100001,DataAnalyst_1.pdf,Candidate_1,Data Science,Data Analyst,7,LLM,Mathematics,Tier-1,"Machine Learning, Power BI, Pandas, Python",...,0.0061,0.888889,"[machine learning, power bi, pandas, python]",0.142857,1.000000,1,0.355934,0,0.503056,0
1,CND_100002,profile_2.pdf,Candidate_2,IT,Senior Software Engineer,10,Masters,Computer Science,Tier-2,"Kubernetes, Git, Docker, Python",...,0.0089,0.857143,"[kubernetes, git, docker, python]",0.000000,1.000000,0,0.047435,1,0.434223,0
2,CND_100003,Legal_candidate_3.pdf,Candidate_3,Legal,Compliance Officer,7,LLM,Law,Tier-1,"Due Diligence, Legal Research, Compliance, Con...",...,0.0056,0.904762,"[due diligence, legal research, compliance, co...",0.000000,1.000000,0,0.212773,0,0.283813,0
3,CND_100004,IT_candidate_4.pdf,Candidate_4,IT,Senior Software Engineer,9,LLM,Computer Science,Tier-1,"Kubernetes, AWS, SQL, Docker",...,0.0089,0.873016,"[kubernetes, aws, sql, docker]",0.000000,1.000000,0,0.212773,1,0.467482,0
4,CND_100005,IT_candidate_5.pdf,Candidate_5,IT,Software Engineer,9,Masters,Information Technology,Tier-1,"Java, Kubernetes, Git, AWS",...,0.0059,0.809524,"[java, kubernetes, git, aws]",0.000000,1.000000,0,0.212773,1,0.467252,0
5,CND_100006,Data Science_candidate_6.pdf,Candidate_6,Data Science,Junior Data Scientist,2,Bachelors,Mathematics,Tier-1,"NLP, Machine Learning, SQL, Python",...,0.0093,0.857143,"[nlp, machine learning, sql, python]",0.142857,0.666667,1,0.355934,0,0.386519,0
6,CND_100007,DevOpsEngineer_7.pdf,Candidate_7,IT,DevOps Engineer,9,NaN,Computer Science,Tier-1,"Kubernetes, AWS, SQL, Java",...,0.0058,0.873016,"[kubernetes, aws, sql, java]",0.000000,1.000000,0,0.000000,1,0.467362,0
7,CND_100008,resume_8_Full_Stack_Developer.pdf,Candidate_8,IT,Full Stack Developer,10,Bachelors,Information Technology,Tier-1,"Kubernetes, AWS, Java, Git",...,0.0063,0.809524,"[kubernetes, aws, java, git]",0.000000,1.000000,0,0.047435,1,0.467187,0
8,CND_100009,resume_9_Cloud_Engineer.pdf,Candidate_9,IT,Cloud Engineer,5,Masters,Information Technology,Tier-2,"AWS, Kubernetes, Java, Ptyhon",...,0.0083,0.825397,"[aws, kubernetes, java, python]",0.142857,1.000000,0,0.048851,1,0.503016,0
9,CND_100010,resume_10_ML_Engineer.pdf,Candidate_10,Data Science,ML Engineer,5,Masters,Mathematics,Tier-3,"Machine Learning, NLP, Power BI, Pythno",...,0.0058,0.888889,"[machine learning, nlp, power bi, python]",0.142857,1.000000,1,0.355934,0,0.502811,0
10,CND_100011,profile_11.pdf,Candidate_11,Data Science,Data Scientist,7,Masters,Data Science,Tier-2,"Machine Learning, Pandas, NLP, Power BI",...,0.0073,0.952381,"[machine learning, pandas, nlp, power bi]",0.142857,1.000000,1,0.094699,1,0.652966,1
11,CND_100012,profile_12.pdf,Candidate_12,IT,Senior Software Engineer,17,Masters,Information Technology,Tier-2,"Python, SQL, AWS, Docker",...,0.0089,0.873016,"[python, sql, aws, docker]",0.142857,1.000000,0,0.047435,1,0.503246,0
12,CND_100013,resume_13_Cloud_Engineer.pdf,Candidate_13,IT,Cloud Engineer,7,MBA,Computer Science,Tier-1,"Python, Linux, Docker, Java",...,0.0091,0.888889,"[python, linux, docker, java]",0.142857,1.000000,0,0.000000,1,0.469728,0
13,CND_100014,profile_14.pdf,Candidate_14,HR,HR Executive,3,LLM,Human Resources,Tier-3,"Recruitment, Employee Engagement, Payroll, HRMS",...,0.0090,0.841270,"[recruitment, employee engagement, payroll, hrms]",0.000000,1.000000,0,0.000000,0,0.250610,0
14,CND_100015,resume_15_Corporate_Lawyer.pdf,Candidate_15,Legal,Corporate Lawyer,6,MBA,NaN,Tier-3,"Due Diligence, Compliance, Legal Research, Con...",...,0.0084,0.936508,"[due diligence, compliance, legal research, co...",0.000000,1.000000,0,0.212773,0,0.284018,0
15,CND_100016,profile_16.pdf,Candidate_16,IT,DevOps Engineer,4,Bachelors,Information Technology,Tier-3,"Git, AWS, Java, Docker",...,0.0071,0.920635,"[git, aws, java, docker]",0.000000,1.000000,0,0.000000,1,0.433948,0
16,CND_100017,SoftwareEngineer_17.pdf,Candidate_17,IT,Software Engineer,6,LLM,Computer Science,Tier-2,"Git, SQL, Kubernetes, Jaav",...,0.0080,0.793651,"[git, sql, kubernetes, java]",0.000000,1.000000,0,0.048851,1,0.434028,0
17,CND_100018,IT_candidate_18.pdf,Candidate_18,IT,Software Engineer,7,Masters,Computer Science,Tier-1,"Kubenretes, Git, Java, SQL",...,0.0064,0.873016,"[kubenretes, git, java, sql]",0.000000,1.000000,0,0.212773,1,0.434033,0
18,CND_100019,HR_candidate_19.pdf,Candidate_19,HR,Talent Acquisition Specialist,3,LLM,Human Resources,Tier-2,"Employee Engagement, Recruitment, HRMS, HR Ana...",...,0.0076,0.809524,"[employee engagement, recruitment, hrms, hr an...",0.000000,1.000000,0,0.212773,0,0.250755,0
19,CND_100020,Data Science_candidate_20.pdf,Candidate_20,Data Science,Data Scientist,10,LLM,Statistics,Tier-3,"Python, Pandas, NLP, Machine Learning",...,0.0056,0.888889,"[python, pandas, nlp, machine learning]",0.142857,1.000000,1,0.092302,0,0.503091,0
20,CND_100021,resume_21_Compliance_Officer.pdf,Candidate_21,Legal,Compliance Officer,10,LLM,Law,Tier-2,"Contract Drafting, Compliance, Legal Research,...",...,0.0094,0.904762,"[contract drafting, compliance, legal research...",0.000000,1.000000,0,0.000000,0,0.284228,0
21,CND_100022,IT_candidate_22.pdf,Candidate_22,IT,Cloud Engineer,3,Bachelors,Computer Science,Tier-2,"Java, SQL, Kubernetes, Linux",...,0.0058,0.825397,"[java, sql, kubernetes, linux]",0.000000,1.000000,0,0.048851,1,0.400490,0
22,CND_100023,profile_23.pdf,Candidate_23,Engineering,Junior Mechanical Engineer,1,Bachelors,Mechanical Engineering,Tier-2,"SolidWorks, CAD, Manufacturing, Quality Control",...,0.0084,0.888889,"[solidworks, cad, manufacturing, quality control]",0.000000,0.333333,0,0.212773,0,0.084008,0
23,CND_100024,IT_candidate_24.pdf,Candidate_24,IT,Full Stack Developer,6,LLM,Information Technology,Tier-2,"Java, SQL, Docker, AWS",...,0.0072,0.873016,"[java, sql, docker, aws]",0.000000,1.000000,0,0.212773,1,0.467382,0
24,CND_100025,DataScientist_25.pdf,Candidate_25,Data Science,Data Scientist,10,LLM,Statistics,Tier-3,"TensorFlow, Power BI, SQL, NLP",...,0.0066,0.920635,"[tensorflow, power bi, sql, nlp]",0.000000,1.000000,1,0.154458,0,0.467352,0
25,CND_100026,profile_26.pdf,Candidate_26,IT,Software Engineer,4,LLM,Information Technology,Tier-3,"Kubernetes, SQL, Linux, Git",...,0.0069,0.857143,"[kubernetes, sql, linux, git]",0.000000,1.000000,0,0.000000,1,0.400650,0
26,CND_100027,profile_27.pdf,Candidate_27,IT,Senior Software Engineer,12,Bachelors,Information Technology,Tier-1,"Kubernetes, Python, SQL, Java",...,0.0083,0.873016,"[kubernetes, python, sql, java]",0.000000,1.000000,0,0.207105,1,0.433973,0
27,CND_100028,IT_candidate_28.pdf,Candidate_28,IT,Junior Software Engineer,1,Bachelors,Computer Science,Tier-3,"AWS, SQL, Java, Kubernetes",...,0.0058,0.873016,"[aws, sql, java, kubernetes]",0.142857,0.333333,0,0.048851,1,0.303106,0
28,CND_100029,DevOpsEngineer_29.pdf,Candidate_29,IT,DevOps Engineer,9,MBA,Computer Science,Tier-3,"Kubernetes, Git, AWS, Linux",...,0.0055,0.857143,"[kubernetes, git, aws, linux]",0.000000,1.000000,0,0.212773,1,0.467092,0
29,CND_100030,DevOpsEngineer_30.pdf,Candidate_30,IT,DevOps Engineer,10,MBA,Computer Science,Tier-2,"AWS, Python, Java, Docker",...,0.0088,0.904762,"[aws, python, java, docker]",0.142857,1.000000,0,0.000000,1,0.503141,0
30,CND_100031,resume_31_Compliance_Officer.pdf,Candidate_31,Legal,Compliance Officer,4,MBA,Law,Tier-3,"Due Diligence, Legal Research, Compliance, Con...",...,0.0066,0.920635,"[due diligence, legal research, compliance, co...",0.000000,1.000000,0,0.000000,0,0.250600,0
31,CND_100032,profile_32.pdf,Candidate_32,Management,Management Consultant,16,MBA,Business Administration,Tier-1,"Risk Management, Strategy, Stakeholder Managem...",...,0.0077,0.888889,"[risk management, strategy, stakeholder manage...",0.000000,1.000000,0,0.207105,0,0.284058,0
32,CND_100033,SoftwareEngineer_33.pdf,Candidate_33,IT,Software Engineer,8,MBA,Information Technology,Tier-1,"Linux, SQL, Kubernetes, Python",...,0.0060,0.841270,"[linux, sql, kubernetes, python]",0.000000,1.000000,0,0.212773,1,0.433908,0
33,CND_100034,profile_34.pdf,Candidate_34,HR,Talent Acquisition Specialist,7,Bachelors,Psychology,Tier-3,"Employee Engagement, Payroll, Recruitment, HR ...",...,0.0075,0.809524,"[employee engagement, payroll, recruitment, hr...",0.000000,1.000000,0,0.048851,0,0.284158,0
34,CND_100035,IT_candidate_35.pdf,Candidate_35,IT,DevOps Engineer,10,LLM,Computer Science,Tier-1,"SQL, Docker, AWS, Linux",...,0.0094,0.841270,"[sql, docker, aws, linux]",0.142857,1.000000,0,0.047435,1,0.503016,0
35,CND_100036,IT_candidate_36.pdf,Candidate_36,IT,Junior Software Engineer,4,MBA,Information Technology,Tier-1,"Java, AWS, Kubernetes, Python",...,0.0064,0.841270,"[java, aws, kubernetes, python]",0.000000,1.000000,0,0.212773,1,0.433978,0
36,CND_100037,Data Science_candidate_37.pdf,Candidate_37,Data Science,Data Scientist,6,Masters,Statistics,Tier-1,"Pandas, Python, TensorFlow, Power BI",...,0.0058,0.904762,"[pandas, python, tensorflow, power bi]",0.142857,1.000000,1,0.094699,0,0.502851,0
37,CND_100038,Legal_candidate_38.pdf,Candidate_38,Legal,Corporate Lawyer,10,MBA,Law,Tier-2,"Compliance, Contract Drafting, Due Diligence, ...",...,0.0059,0.857143,"[compliance, contract drafting, due diligence,...",0.000000,1.000000,0,0.047435,0,0.284028,0
38,CND_100039,SeniorSoftwareEngineer_39.pdf,Candidate_39,IT,Senior Software Engineer,17,MBA,Computer Science,Tier-3,"AWS, SQL, Docker, Python",...,0.0067,0.857143,"[aws, sql, docker, python]",0.142857,1.000000,0,0.047435,1,0.503051,0
39,CND_100040,profile_40.pdf,Candidate_40,IT,DevOps Engineer,8,Bachelors,Computer Science,Tier-1,"Docker, Python, Linux, SQL",...,0.0084,0.857143,"[docker, python, linux, sql]",0.000000,1.000000,0,0.000000,1,0.434158,0
40,CND_100041,SeniorProjectManager_41.pdf,Candidate_41,Management,Senior Project Manager,9,Bachelors,Business Administration,Tier-2,"Risk Management, Strategy, Stakeholder Managem...",...,0.0060,0.888889,"[risk management, strategy, stakeholder manage...",0.000000,1.000000,0,0.048851,0,0.283968,0
41,CND_100042,IT_candidate_42.pdf,Candidate_42,IT,Junior Software Engineer,3,NaN,Information Technology,Tier-2,"Linux, Python, Git, Java",...,0.0089,0.904762,"[linux, python, git, java]",0.000000,1.000000,0,0.048851,1,0.400880,0
42,CND_100043,FullStackDeveloper_43.pdf,Candidate_43,IT,Full Stack Developer,8,Bachelors,Computer Science,Tier-1,"SQL, Python, Kubernetes, Docker",...,0.0061,0.825397,"[sql, python, kubernetes, docker]",0.142857,1.000000,0,0.000000,1,0.469583,0
43,CND_100044,Legal_candidate_44.pdf,Candidate_44,Legal,Legal Associate,3,Bachelors,Law,Tier-2,"Compliance, Contract Drafting, Due Diligence, ...",...,0.0059,0.888889,"[compliance, contract drafting, due diligence,...",0.000000,1.000000,0,0.000000,0,0.250585,0
44,CND_100045,DevOpsEngineer_45.pdf,Candidate_45,IT,DevOps Engineer,3,MBA,Information Technology,Tier-3,"AWS, Kubernetes, SQL, Python",...,0.0073,0.873016,"[aws, kubernetes, sql, python]",0.142857,1.000000,0,0.048851,1,0.469708,0
45,CND_100046,DataAnalyst_46.pdf,Candidate_46,Data Science,Data Analyst,4,LLM,Data Science,Tier-1,"Power BI, Pandas, SQL, Machine Learning",...,0.0070,0.888889,"[power bi, pandas, sql, machine learning]",0.142857,1.000000,1,0.159064,1,0.619763,1
46,CND_100047,resume_47_Junior_Software_Engineer.pdf,Candidate_47,IT,Junior Software Engineer,3,MBA,Information Technology,Tier-2,"Java, Kubernetes, Docker, Git",...,0.0087,0.904762,"[java, kubernetes, docker, git]",0.000000,1.000000,0,0.000000,1,0.400745,0
47,CND_100048,HRExecutive_48.pdf,Candidate_48,HR,HR Executive,3,LLM,Psychology,Tier-2,"HRMS, Recruitment, HR Analytics, Payroll",...,0.0086,0.873016,"[hrms, recruitment, hr analytics, payroll]",0.000000,1.000000,0,0.212773,0,0.250790,0
48,CND_100049,resume_49_Data_Analyst.pdf,Candidate_49,Data Science,Data Analyst,3,MBA,Mathematics,Tier-3,"Machine Learning, Power BI, SQL, Python",...,0.0064,0.920635,"[machine learning, power bi, sql, python]",0.142857,1.000000,1,0.355934,0,0.469593,0
49,CND_100050,profile_50.pdf,Candidate_50,Management,Project Coordinator,1,Bachelors,Management,Tier-2,"Stakeholder Management, Risk Management, Strat...",...,0.0089,0.888889,"[stakeholder management, risk management, stra...",0.000000,0.333333,0,0.212773,0,0.084203,0

In [419]:
df[['final_score', 'selected']].head(50)

    final_score  selected
0      0.503056         0
1      0.434223         0
2      0.283813         0
3      0.467482         0
4      0.467252         0
5      0.386519         0
6      0.467362         0
7      0.467187         0
8      0.503016         0
9      0.502811         0
10     0.652966         1
11     0.503246         0
12     0.469728         0
13     0.250610         0
14     0.284018         0
15     0.433948         0
16     0.434028         0
17     0.434033         0
18     0.250755         0
19     0.503091         0
20     0.284228         0
21     0.400490         0
22     0.084008         0
23     0.467382         0
24     0.467352         0
25     0.400650         0
26     0.433973         0
27     0.303106         0
28     0.467092         0
29     0.503141         0
30     0.250600         0
31     0.284058         0
32     0.433908         0
33     0.284158         0
34     0.503016         0
35     0.433978         0
36     0.502851         0
37     0.284028         0
38     0.503051         0
39     0.434158         0
40     0.283968         0
41     0.400880         0
42     0.469583         0
43     0.250585         0
44     0.469708         0
45     0.619763         1
46     0.400745         0
47     0.250790         0
48     0.469593         0
49     0.084203         0

In [420]:
X = df[
    ['skill_match_score', 'exp_match_score', 'domain_match',
     'education_match', 'flag_score',
     'keyword_score_norm', 'profile_score_norm', 'length_score']
]

y = df['selected']

In [421]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [422]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [423]:
y_pred = model.predict(X_test)

In [424]:
#accuracy 

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0

In [425]:
import pandas as pd

importance = pd.Series(model.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

domain_match          0.361013
education_match       0.360796
length_score          0.053389
skill_match_score     0.049036
keyword_score_norm    0.048928
exp_match_score       0.048127
flag_score            0.041128
profile_score_norm    0.037583
dtype: float64

In [426]:
# Save model
import pickle
with open("../models/model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully!")

Model saved successfully!

In [427]:
df['selected'].value_counts()

selected
0    4727
1     273
Name: count, dtype: int64

# Observed Biased in the Model
### We observed the selected count is very low i.e 273 and it biased 
#### Hence we will include top %
#### top_percent = 0.3   # means top 30%

In [428]:
top_percent = 0.3 
cutoff = df['final_score'].quantile(1 - top_percent)
df['selected'] = df['final_score'].apply(lambda x: 1 if x >= cutoff else 0)

In [429]:
df['selected'].value_counts()

selected
0    3498
1    1502
Name: count, dtype: int64

# We observed the selected count i.e 1502 and it not biased 
## Hence now we can go with train and split

In [430]:
X = df[
    ['skill_match_score', 'exp_match_score', 'domain_match',
     'education_match', 'flag_score',
     'keyword_score_norm', 'profile_score_norm', 'length_score']
]

y = df['selected']

In [431]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Why We Use RandomForestClassifier

RandomForestClassifier is a Machine Learning algorithm used for classification problems.

In this project, we want to predict:

- Selected = 1
- Rejected = 0

So this becomes a classification problem.

---

# Why Random Forest?

## 1. Works well with numeric features

Our model uses numeric resume scores like:

- Skill score
- Experience score
- Domain score
- Education score

Random Forest works very well with these types of structured numeric features.

---

## 2. Gives good accuracy

Random Forest usually gives good prediction accuracy without requiring heavy tuning.

---

## 3. Handles multiple factors together

Resume screening depends on many factors:

- Skills
- Experience
- Education
- Domain match
- Keywords

Random Forest can understand the relationship between all these features together.

---

## 4. Reduces overfitting

Random Forest creates multiple Decision Trees instead of one tree.

Each tree gives its own prediction.

Example:

- Tree 1 → Selected
- Tree 2 → Selected
- Tree 3 → Rejected

Final prediction is based on majority voting.

This helps reduce overfitting and improves stability.

---

## 5. Easy to train and use

Random Forest is:
- Simple to implement
- Fast to train
- Good for beginner and intermediate ML projects

---

# Why It Is Good for Resume Screening

Resume screening contains many scoring parameters.

Random Forest can analyze:
- candidate skills
- experience
- education
- profile quality

and make a final prediction based on all these factors.

---

# Simple Summary

We use RandomForestClassifier because:

- It is good for classification problems
- Works well with resume scoring features
- Gives good accuracy
- Handles multiple inputs together
- Reduces overfitting
- Easy to implement in real projects

In [432]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(class_weight='balanced')
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced')

In [433]:
y_pred = model.predict(X_test)

## Accuracy Score

In [434]:

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.999

In [435]:
print(len(X_train))
print(len(y_train))
print(type(X_train))
print(type(y_train))

4000
4000
<class 'pandas.DataFrame'>
<class 'pandas.Series'>

In [436]:
import pandas as pd

importance = pd.Series(model.feature_importances_, index=X.columns)
print(importance.sort_values(ascending=False))

skill_match_score     0.560948
domain_match          0.151384
flag_score            0.116508
exp_match_score       0.053402
education_match       0.046776
keyword_score_norm    0.028412
profile_score_norm    0.024181
length_score          0.018389
dtype: float64

# Save model

In [437]:
import pickle
with open("../models/model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model saved successfully!")

Model saved successfully!

## Accuracy Report

In [438]:
preds = model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, preds))
print("\\nClassification Report:\\n")
print(classification_report(y_test, preds))

Accuracy: 0.999
\nClassification Report:\n
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       709
           1       1.00      1.00      1.00       291

    accuracy                           1.00      1000
   macro avg       1.00      1.00      1.00      1000
weighted avg       1.00      1.00      1.00      1000